url: "https://hugo-liz.github.io"
baseurl: ""

name: 党国浩
title: 产品经理
email: dangguohao66@163.com
location: 南京-中国

about_profile_image: images/profile.jpg
about_content: 跨领域数字化解决方案专家，拥有复杂系统0-1建设能力，主导政企/文化/ERP领域多款系统从需求到落地。产品方案支撑部门斩获1600W项目业绩，沉淀3项地方性行业数据标准。运用Tableau/SQL进行数据治理与监控，优化流程并输出决策报告。

content:
  - title: 工作经历
    layout: list
    content:
      - layout: left
        title: 江苏齐同浩渺信息科技有限公司
        sub_title: 产品经理
        caption: 2025.07 - 至今
        description: "负责SAST、SCA产品矩阵全周期管理，主导版本迭代规划与需求设计。完成AI代码审计产品全链路管理，通过AI能力实现漏洞智能定位与修复建议。主导设计安全服务业务平台，提升安服人员工作效率约30%。"

      - layout: left
        title: 中建八局智慧科技公司（定向外包）
        sub_title: ERP产品经理
        caption: 2023.11 - 2025.07
        description: "负责中建八局三公司管理平台中项目、分包商管理、方案管理、质量管理、财务管理系统设计。梳理并设计业务及审批流程，节约31.2%人力成本，提升25.4%审批效率。定期监控系统数据，制作数据分析报告，推动数据治理项目落地。"

      - layout: left
        title: 中国知网
        sub_title: 产品经理
        caption: 2021.03 - 2023.08
        description: "针对党政数字化、纪念馆、公共图书馆等行业开展需求调研、竞品分析、系统原型设计。主导行业分析及产品汇报，提供售前支持，跨团队协作推动产品上线。成功申报3项地方性数据标准，帮助部门累计获得1600W营收。"

  - title: 项目经历
    layout: list
    content:
      - layout: left
        title: DAMP数据资产管理平台
        sub_title: 中建八局第三建设有限公司
        caption: 2024.01 - 2024.11
        description: "解决公司内部数据孤岛问题，构建统一资产目录与数据集市共享机制。主导设计6大核心模块，覆盖1200+业务实体/指标资产。减少信息化开发成本300万元，主数据填报流程压缩67%，年节省人力工时1200+小时。"

      - layout: left
        title: 文化遗产数字化平台建设项目
        sub_title: 雨花台烈士陵园管理局
        caption: 2022.12 - 2023.08
        description: "主导投标文件技术方案编写与评审，成功助力项目中标，创收827万元。主导系统功能设计，利用Axure产出可交互原型，构建系统知识图谱，极大提升用户资源检索效率。"

      - layout: left
        title: 江苏省公共图书馆在线学习平台
        sub_title: 江苏省图书馆
        caption: 2022.12 - 2023.05
        description: "主导课程体系与在线评测系统设计，构建三大数据看板，使用Axure RP输出高保真交互原型。实现40万元项目创收，以98%客户满意度赢得长期合作协议。"

  - title: 专业技能
    layout: text
    content: "精通：Office、Axure RP、Axhub、XMind、Draw.IO | 熟练：SQL、Tableau | 证书：软考中级系统集成项目管理工程师、PMI-PMP（3A）| 语言：英语CET-6 | 兴趣：摄影（视觉中国签约摄影师）"

  - title: 教育背景
    layout: list
    content:
      - layout: left
        title: 南京工程学院
        sub_title: 全日制本科 · 计算机科学与技术
        caption: 2016.09 - 2020.06

footer_show_references: false
remote_theme: sproogen/modern-resume-theme
plugins:
  - jekyll-remote-theme
